### ISSUE TITLE
Required for installation video

### ISSUE THREAD

**Issue by lsz7575** [hugsy/CFB#14]
Bad For My English.
Can You Teach Me How To Install It?
I Haven’t Installed It For a Day.
It To Hard.

I Try

CFB_App_0.1.0.0_Alpha.zip ->
CFB Monitor View  ->  Settings  -> IRP Broker location
\\192.168.127.135\pipe\cfb
pipe:\\pipe\cfb
\\.\pipe\cfb
file://192.168.127.135/pipe/cfb

But None Of Them Work.

This Tool is Cool. Very useful for learning The kernel. I Think I Need it.
Have a Nice Day.
: )

**Comment by lsz7575** [comment]
我的英文很差..
请问您可以出一个视频教我如何安装CFB吗?
我今天安装了一天没装好.
我尝试过好多设置都不工作.
这个软件非常有意思,对于学习内核非常有帮助,我想我需要它来帮助我学习内核 .
祝您今天过得开心     :)

**Comment by hugsy** [comment]
The released alpha version has not been compiled with named pipe IIRC. In `IRP Broker location just use `tcp://ip.of.broker:port`

For example: `tcp://192.168.127.135:1337`

**Comment by lsz7575** [comment]
> The released alpha version has not been compiled with named pipe IIRC. In `IRP Broker location just use `tcp://ip.of.broker:port`
> 
> For example: `tcp://192.168.127.135:1337`

I get it.
I really appreciate your help.
